# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "HackHub"
description: > # this means to ignore newlines until "email:"
   Hello, World.

email: helloworld@hackhub.ca
#blog logo
logo: "/assets/images/hh_logo.png"
# blog cover
cover: "/assets/images/header_image.jpg"

name: 'HackHub'
author: 'HackHub'
author_image: "/assets/images/hh_logo.png"

paginate: 5

url: "http://hackhub.ca/" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon: twitter
    url: https://twitter.com/dirkfabisch
    desc: Follow us on Twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon: github
    url: https://github.com/HackHub
    desc: Fork us on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
